config/routes.rb
# Add your custom routes here.  If in config/routes.rb you would
# add <tt>map.resources</tt>, here you would add just <tt>resources</tt>

resources :profiles

resources :streams, :only => [:index, :show]

with_options(:controller => 'groups') do |group|
  group.tag_groups       '/groups/tag/:tag',                         :action => 'tag'
end

resources :groups, :collection => { :search => :get }, :member => { :join => :get, :leave => :get }

namespace(:member) do |member|
  member.resources :profiles
  member.resources :groups
  member.with_options(:controller => 'groups') do |group|
    group.group_pending_members '/:id/members/pending',         :action => 'pending_members'
    group.group_accept_member   '/:id/members/:user_id/accept', :action => 'accept_member'
    group.group_reject_member   '/:id/members/:user_id/reject', :action => 'reject_member'
  end
  member.with_options(:controller => 'friendships') do |friendship|
    friendship.add_friend     '/friend/:friend_id/add',     :action => 'add_friend'
    friendship.confirm_friend '/friend/:friend_id/confirm', :action => 'confirm_friend'
    friendship.follow_user    '/follow/:friend_id',         :action => 'follow'
    friendship.unfollow_user  '/unfollow/:friend_id',       :action => 'unfollow'
  end
  member.with_options(:controller => 'sharings') do |sharing|
    sharing.share '/share/:shareable_type/:shareable_id', :action => 'index'
    sharing.share_with_group '/group/:id/share/:shareable_type/:shareable_id', :action => 'share'
  end
end

namespace(:admin) do |admin|
  admin.resources :groups, :member => { :activate => :post}
end

# => oauth support
resources :oauth_clients
authorize     '/oauth/authorize',     :controller=>'oauth', :action=>'authorize'
request_token '/oauth/request_token', :controller=>'oauth', :action=>'request_token'
access_token  '/oauth/access_token',  :controller=>'oauth', :action=>'access_token'
test_request  '/oauth/test_request',  :controller=>'oauth', :action=>'test_request'

x1 '/oauth_test',     :controller=>'oauth_test', :action=>'test'
x2 '/oauth_callback', :controller=>'oauth_test', :action=>'callback'
# => oauth support

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController

  def index
    @order = params[:order] || 'name'
    @page = params[:page] || '1'
    @groups = Group.paginate :per_page => 20,
                             :page => @page,
                             :order => "#{@order} ASC"
  end

  def edit
    @group = Group.find(params[:id])
  end
  
  def update
    @group = Group.find(params[:id])    
    @group.update_attributes!(params[:group])
    @group.save
    flash[:ok] =  I18n.t("tog_social.groups.admin.updated", :name => @group.name) 
    redirect_to edit_admin_group_path(@group)
  end  

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |wants|
      wants.html do
        flash[:ok]= I18n.t("tog_social.groups.admin.deleted")
        redirect_to admin_groups_path
      end
    end
  end

  def activate
    @group = Group.find(params[:id])
    @group.activate!
    respond_to do |wants|
      if @group.activate!
        wants.html do
          render :text => "<span>#{I18n.t("tog_social.groups.admin.activated")}</span>"
        end
      end
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :login_required, :only => [:join, :leave]
  before_filter :load_group, :only => [:show, :join, :leave, :members, :accept_invitation, :reject_invitation, :share]

  def index
    @order = params[:order] || 'created_at'
    @page = params[:page] || '1'
    @asc = params[:asc] || 'desc'
    @groups = Group.active.public.paginate  :per_page => 10,
                                            :page => @page,
                                            :order => @order + " " + @asc
    respond_to do |format|
      format.html
      format.rss { render(:layout => false) }
    end
  end

  def search
    @order = params[:order] || 'name'
    @page = params[:page] || '1'
    @search_term = params[:search_term]
    term = '%' + @search_term + '%'
    @asc = params[:asc] || 'asc'
    @groups = Group.active.public.paginate  :per_page => 10,
                                            :conditions => ["(name like ? or description like ?)", term, term],
                                            :page => @page,
                                            :order => @order + " " + @asc
    respond_to do |format|
       format.html { render :template => "groups/index"}
       format.xml  { render :xml => @groups }
    end
  end

  def show
  end

  def members
  end


  def tag
    @tag = params[:tag]
    @groups = Group.active.public.find_tagged_with(@tag)
    respond_to do |format|
      format.html # tag.html.erb
      format.xml  { render :xml => @groups.to_xml }
    end
  end

  def join
    if @group.members.include? current_user
      flash[:notice] = I18n.t("tog_social.groups.site.already_member")
    else
      if @group.pending_members.include? current_user
        flash[:notice] = I18n.t("tog_social.groups.site.request_waiting")
      else
        @group.join(current_user)
        if @group.moderated == true
          GroupMailer.deliver_join_request(@group, current_user)
          flash[:ok] = I18n.t("tog_social.groups.site.request_received")
        else
          @group.activate_membership(current_user)
          flash[:ok] = I18n.t("tog_social.groups.site.welcome", :name => @group.name)
        end
      end
    end
    redirect_to group_url(@group)
  end

  def leave
    if !@group.members.include?(current_user) && !@group.pending_members.include?(current_user)
      flash[:error] = I18n.t("tog_social.groups.site.not_member")
    else
      if @group.moderators.include?(current_user) && @group.moderators.size == 1
        flash[:error] = I18n.t("tog_social.groups.site.last_moderator")
      else
        @group.leave(current_user)
        #todo: eliminar cuando este claro que sucede si un usuario ya es miembro
        flash[:ok] = I18n.t("tog_social.groups.site.leaved")
      end
    end
    redirect_to member_groups_path
  end
  
  def accept_invitation
    if(@group.accept_invitation(current_user))
      flash[:ok] = I18n.t("tog_social.groups.site.invite.invitation_accepted")
    else
      flash[:error] = I18n.t("tog_social.groups.site.invite.you_are_not_invited")
    end
    redirect_to group_path(@group)
  end
  
  def reject_invitation
    if(@group.leave(current_user))
      flash[:ok] = I18n.t("tog_social.groups.site.invite.invitation_rejected")
    else
      flash[:error] = I18n.t("tog_social.groups.site.invite.you_are_not_invited")
    end
    redirect_to group_path(@group)
  end
  
  protected
    def load_group
      #TODO be more specific with this error control
      begin
        @group = Group.find(params[:id])
        raise I18n.t("tog_social.site.groups.unactive") unless @group.active?
      rescue
        flash[:error] = I18n.t("tog_social.groups.site.not_found")
        redirect_to groups_path
      end
    end

    def send_message_to_moderators(group, user, subject, body)
      group.moderators.each do |moderator|
        message = Message.new(
          :from     => user,
          :to       => moderator,
          :subject  => subject,
          :content  => body)
        message.dispatch!
      end
    end
end

app/controllers/member/friendships_controller.rb
class Member::FriendshipsController < Member::BaseController

  before_filter :find_friend_profile

  def add_friend
    if @friend.add_follower(current_user.profile)
      flash[:ok]=I18n.t("tog_social.friendships.member.friend.request", :friend_name => @friend.full_name)
      Message.new(
        :from => current_user,
        :to   => @friend.user,
        :subject => I18n.t("tog_social.friendships.member.mail.request_friend.subject", :user_name => current_user.profile.full_name),
        :content => I18n.t("tog_social.friendships.member.mail.request_friend.content", 
                           :user_name   => current_user.profile.full_name, 
                           :friend_name => @friend.full_name, 
                           :user_profile_url => profile_url(current_user.profile) , 
                           :confirm_url      => member_confirm_friend_url(current_user.profile))
      ).dispatch!
    end
    redirect_back_or_default(profile_path(current_user.profile))
  end

  def confirm_friend
    if @friend.follows?(current_user.profile) && @friend.add_follower(current_user.profile)
      flash[:ok]=I18n.t("tog_social.friendships.member.friend.confirmed", :friend_name => @friend.full_name)
      Message.new(
        :from => current_user,
        :to   => @friend.user,
        :subject => I18n.t("tog_social.friendships.member.mail.confirm_friend.subject", :user_name => current_user.profile.full_name),
        :content => I18n.t("tog_social.friendships.member.mail.confirm_friend.content", 
                           :user_name   => current_user.profile.full_name, 
                           :friend_name => @friend.full_name, 
                           :user_profile_url => profile_url(current_user.profile)) 
      ).dispatch! 
    end

    redirect_back_or_default(profile_path(current_user.profile))
  end

  def follow
    if @friend.add_follower(current_user.profile)
      flash[:ok]=I18n.t("tog_social.friendships.member.followed", :user_name => @friend.full_name)
      Message.new(
        :from => current_user,
        :to   => @friend.user,
        :subject => I18n.t("tog_social.friendships.member.mail.follow.subject", :user_name => current_user.profile.full_name),
        :content => I18n.t("tog_social.friendships.member.mail.follow.content", 
                           :user_name   => current_user.profile.full_name, 
                           :friend_name => @friend.full_name, 
                           :user_profile_url => profile_url(current_user.profile))
      ).dispatch!
    end
    redirect_back_or_default(profile_path(current_user.profile))    
  end

  def unfollow
    if @friend.remove_follower(current_user.profile)
      flash[:ok]=I18n.t("tog_social.friendships.member.unfollowed", :user_name => @friend.full_name)
      Message.new(
        :from => current_user,
        :to   => @friend.user,
        :subject => I18n.t("tog_social.friendships.member.mail.unfollow.subject", :user_name => current_user.profile.full_name),
        :content => I18n.t("tog_social.friendships.member.mail.unfollow.content", 
                           :user_name   => current_user.profile.full_name, 
                           :friend_name => @friend.full_name, 
                           :user_profile_url => profile_url(current_user.profile))
      ).dispatch!
    end
    redirect_back_or_default(profile_path(current_user.profile))    
  end

  private
    def find_friend_profile
      @friend = Profile.find(params[:friend_id])
      unless @friend
        flash[:error] = I18n.t("tog_social.friendships.member.not_found", :id => params[:friend_id].to_s)
        redirect_to profiles_path
      end
    end
end

app/controllers/member/groups_controller.rb
class Member::GroupsController < Member::BaseController

  before_filter :find_group, :except => [:index, :new, :create]
  before_filter :check_moderator, :except => [:index, :new, :create, :invite, :accept_invitation, :reject_invitation]

  def index
    @moderator_memberships = current_user.moderator_memberships
    @plain_memberships = current_user.plain_memberships
  end

  def create
    @group = Group.new(params[:group])
    @group.author = current_user
    @group.save


    if @group.errors.empty?

      @group.join(current_user, true)
      #    @group.activate_membership(current_user)

      if current_user.admin == true || Tog::Config['plugins.tog_social.group.moderation.creation'] != true
         @group.activate!
         flash[:ok] = I18n.t("tog_social.groups.member.created")
         redirect_to group_path(@group)
      else

        admins = User.find_all_by_admin(true)        
        admins.each do |admin|
          Message.new(
            :from => current_user,
            :to   => admin,
            :subject => I18n.t("tog_social.groups.member.mail.activation_request.subject", :group_name => @group.name),
            :content => I18n.t("tog_social.groups.member.mail.activation_request.content", 
                               :user_name   => current_user.profile.full_name, 
                               :group_name => @group.name, 
                               :activation_url => edit_admin_group_url(@group)) 
          ).dispatch!     
        end

        flash[:warning] = I18n.t("tog_social.groups.member.pending")
        redirect_to groups_path
      end
    else
      render :action => 'new'
    end

  end

  def update
    @group.update_attributes!(params[:group])
    @group.tag_list = params[:group][:tag_list]
    @group.save
    flash[:ok] =  I18n.t("tog_social.groups.member.updated", :name => @group.name) 
    redirect_to group_path(@group)
  end

  def reject_member
    user = User.find(params[:user_id])
    if !user
      flash[:error] = I18n.t("tog_social.groups.member.user_doesnot_exists")
      redirect_to pending_members_paths(@group)
      return
    end
    @group.leave(user)
    if @group.membership_of(user)
      GroupMailer.deliver_reject_join_request(@group, current_user, user)
      flash[:ok] = I18n.t("tog_social.groups.member.user_rejected", :name => user.profile.full_name) 
    else
      flash[:error] = I18n.t("tog_social.groups.member.error") 
    end
    redirect_to member_group_pending_members_url(@group)
  end

  def accept_member
    user = User.find(params[:user_id])
    if !user
      flash[:error] = I18n.t("tog_social.groups.member.user_doesnot_exists")
      redirect_to pending_members_paths(@group)
      return
    end
    @group.activate_membership(user)
    if @group.members.include? user
      GroupMailer.deliver_accept_join_request(@group, current_user, user)
      flash[:ok] = I18n.t("tog_social.groups.member.user_accepted", :name => user.profile.full_name)
    else
      flash[:error] = I18n.t("tog_social.groups.member.error") 
    end
    redirect_to member_group_pending_members_url(@group)
  end

  def invite
    @group = Group.find(params[:membership][:group_id])
    user = User.find(params[:membership][:user_id])
    if @group.can_invite?(current_user)
      if @group.members.include? user
        flash[:notice] = I18n.t("tog_social.groups.site.already_member")
      else
        if @group.invited_members.include? user
          flash[:error] = I18n.t("tog_social.groups.site.invite.already_invited")
        else
          @group.invite(user)
          @message = Message.new(
          :from => current_user,
          :to => user,
          :subject => I18n.t("tog_social.groups.member.mail.invitation.subject", :group=>@group.name),
          :content => render_to_string(:partial => 'invite_mail', :locals =>{:group=>@group})
          )
          @message.dispatch!
          flash[:ok] = I18n.t("tog_social.groups.site.invite.invited")
        end
      end
    else
      flash[:error] = flash[:error] = I18n.t("tog_social.groups.site.invite.you_could_not_invite")
    end
    redirect_to profile_path(user.profile)
  end

  protected


  def find_group
    @group = Group.find(params[:id]) if params[:id]
  end

  def check_moderator
    unless @group.moderators.include? current_user
      flash[:error] = I18n.t("tog_social.groups.member.not_moderator") 
      redirect_to group_path(@group)
    end
  end

end

app/controllers/member/preferences_controller.rb
class Member::PreferencesController < Member::BaseController

  def edit
    @preferences = current_user.preferences
  end
  
  def update
    params[:preferences].each do |k,v|
      current_user.write_preference(k, v)
    end
    current_user.save!
    flash[:ok] = I18n.t('tog_social.preferences.member.saved')
    redirect_to :back
  end

end

app/controllers/member/profiles_controller.rb
class Member::ProfilesController < Member::BaseController

  def edit
    @profile = current_user.profile
  end

  def update
    profile = current_user.profile
    profile.update_attributes!(params[:profile])
    profile.save
    flash[:ok] = I18n.t("tog_social.profiles.member.updated") 
    redirect_to profile_path(profile)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper

  def tag_cloud_groups(classes)
    tags = Group.tag_counts(:conditions => "state= 'active' and private = 0")
    return if tags.empty?
    max_count = tags.sort_by(&:count).last.count.to_f
    tags.each do |tag|
      index = ((tag.count / max_count) * (classes.size - 1)).round
      yield tag, classes[index]
    end
  end

  def image_for_group(group, size, options={})
    return if !group
    if group.image?
      photo_url = group.image.url(size)
      options.merge!(:alt => "Photo for group: #{group.name}")
      return image_tag(photo_url, options) if photo_url
    else
      return image_tag("/tog_social/images/#{config["plugins.tog_social.group.image.default"]}", options)
    end
  end


  def last_groups(limit=3)
    Group.find(:all,:conditions => ["state= ? and private = ?", 'active', false],:order => "created_at desc", :limit => limit)
  end


  def i_am_member_of(group)
    return group.members.include?(current_user)
  end
  def i_am_moderator_of(group)
    return group.moderators.include?(current_user)
  end

end

app/views/member/groups/edit.html.erb
<div class="titleB"><%= I18n.t('tog_social.groups.member.edit_group', :group => @group.name) %></div>
<br/>
<%= error_messages_for :group %>

<% form_for(@group, :url => member_group_path(@group), :html => { :multipart => true, :method => :put}) do |f| %>
  <fieldset>
    <div class="fields">
      <p>
        <label for="group_name"><%= I18n.t('tog_social.groups.model.name') %></label>
        <%= f.text_field  :name, :class => 'fieldbox wide' %>
      </p>
      <p>
        <label for="group_description"><%= I18n.t('tog_social.groups.model.description') %></label>
        <%= f.text_area  :description, :class => 'fieldbox wide', :size => '60x10' %></dd>
      </p>
      <p>
        <label for="group_tag_list"><%= I18n.t('tog_social.tags.tags') %></label>
        <%= f.text_field  :tag_list, :class => 'fieldbox' %><br/>
        <span class="helpinfo"><%= I18n.t('tog_social.tags.separated_by_comma') %></span>
      </p>
      <p>
        <label for="group_image"><%= I18n.t('tog_social.groups.model.image') %></label>
        <%= image_for_group(@group, 'medium') %><br/>
        <%= file_field "group", "image" %><br/>
        <span class="helpinfo"><%= I18n.t('tog_social.groups.model.image_help') %></span>
      </p>
      <p>
        <label for="group_private" class="nolabel"><%= f.check_box :private %> <%= I18n.t('tog_social.groups.model.private') %></label><br/>
        <span class="helpinfo"><%= I18n.t('tog_social.groups.model.private_help') %></span>
      </p>
      <p>
        <label for="group_moderated" class="nolabel"><%= f.check_box :moderated %> <%= I18n.t('tog_social.groups.model.moderated') %></label><br/>
        <span class="helpinfo"><%= I18n.t('tog_social.groups.model.moderated_help') %></span>
      </p>
    </div>
  </fieldset>

  <div class="actions">
    <%= f.submit I18n.t('tog_social.groups.member.update'),:class=>"button mainaction" %>
  </div>
<% end %>

app/views/member/groups/index.html.erb
<p><%= link_to I18n.t('tog_social.groups.site.create_group'), new_member_group_path, :class => 'button add' %></p>

<div class="portlet portletB" id="profiles_list">
    <h2><span><%= I18n.t('tog_social.groups.model.moderated_by_you') %></span></h2>
    <div class="portlet_content">
        <ul>
          <% @moderator_memberships.each do |membership|%>
            <li>
              <div class="img"><%=link_to image_for_group(membership.group, 'small'), group_path(membership.group)%></div>
              <div class="info">
                <div class="title"><%= link_to membership.group.name, group_path(membership.group) %></div>
                <div id="actions">
                <%= link_to I18n.t('tog_social.groups.member.edit'), edit_member_group_path(membership.group) -%>
                <%= link_to I18n.t('tog_social.groups.member.members_pending', :size => membership.group.pending_members.size), member_group_pending_members_path(membership.group) %>
                </div>
              </div><!--  fin info -->
            <li>
          <%end%>
        </ul>
    </div>
</div>

<div class="portlet portletB" id="profiles_list">
    <h2><span><%= I18n.t('tog_social.groups.member.group_member') %></span></h2>
    <div class="portlet_content">
        <ul>
          <% @plain_memberships.each do |membership|%>
            <li>
              <div class="img"><%=link_to image_for_group(membership.group, 'small'), group_path(membership.group)%></div>
              <div class="info">
                <div class="title"><%= link_to membership.group.name, group_path(membership.group) %></div>
                <div id="actions">
                  <%= I18n.t('tog_social.groups.model.member_status') %>: <%=membership.state%>
                <br/>
                <%= link_to I18n.t('tog_social.groups.site.leave'), leave_group_path(membership.group), :confirm => I18n.t('tog_social.groups.site.leave_confirm'), :class => 'delete' %>
                </div>
              </div><!--  fin info -->
            <li>
          <%end%>
        </ul>
    </div>
</div>

app/views/member/groups/my_groups.html.erb
<p><%= link_to 'Create new group', new_member_group_path, :class => 'button add' %></p>

<div class="portlet portletB" id="profiles_list">
    <h2><span>Groups moderated by you</span></h2>
    <div class="portlet_content">
        <ul>
					<% @moderator_memberships.each do |membership|%>
	          <li>
	          	<div class="img"><%=link_to image_for_group(membership.group, 'small'), group_path(membership.group)%></div>
			        <div class="info">
			          <div class="title"><%= link_to membership.group.name, group_path(membership.group) %></div>
			        </div><!--  fin info -->
						<li>
					<%end%>
        </ul>
    </div>    
</div>

<div class="portlet portletB" id="profiles_list">
    <h2><span>Groups you are a plain member of</span></h2>
    <div class="portlet_content">
        <ul>
					<% @plain_memberships.each do |membership|%>
	          <li>
	          	<div class="img"><%=link_to image_for_group(membership.group, 'small'), group_path(membership.group)%></div>
			        <div class="info">
			          <div class="title"><%= link_to membership.group.name, group_path(membership.group) %></div>
								<div id="actions">
									Status: <%=membership.state%>
								<br/>
								<%= link_to 'Leave this group', leave_group_path(membership.group), :confirm => 'Are you sure you want to leave this group?', :class => 'delete' %>
								</div>
			        </div><!--  fin info -->
						<li>
					<%end%>
        </ul>
    </div>    
</div>

app/views/member/groups/new.html.erb
<div class="titleB"><%= I18n.t('tog_social.groups.site.create_group') %></div>
<br />

<% if @group && !@group.errors.empty? -%>
<div class="error">
  <%= error_messages_for :group %>
</div>
<% end -%>

<% form_for(:group, :url=>member_groups_path, :html=>{:multipart=>true}) do |f| %>
  <fieldset>
    <legend><%= I18n.t('tog_social.groups.site.details') %></legend>
    <div class="fields">
      <p>
        <label for="group_name"><%= I18n.t('tog_social.groups.model.name') %></label>
        <%= f.text_field  :name, :class => 'fieldbox wide', :size => 35 %>
      </p>
      <p>
        <label for="group_description"><%= I18n.t('tog_social.groups.model.description') %></label>
        <%= f.text_area  :description, :class => 'fieldbox wide', :size => '60x10' %></dd>
      </p>
      <p>
        <label for="group_tag_list"><%= I18n.t('tog_social.tags.tags') %></label>
        <%= f.text_field  :tag_list, :class => 'fieldbox', :size => 35 %><br/>
        <span class="helpinfo"><%= I18n.t('tog_social.tags.separated_by_comma') %></span>
      </p>
      <p>
        <label for="group_image"><%= I18n.t('tog_social.groups.model.image') %></label>
        <%= image_for_group(@group, 'medium') %><br/>
        <%= file_field "group", "image" %><br/>
        <span class="helpinfo"><%= I18n.t('tog_social.groups.model.image_help') %></span>
      </p>
      <p>
        <label for="group_private" class="nolabel"><%= f.check_box :private %> <%= I18n.t('tog_social.groups.model.private') %></label><br/>
        <span class="helpinfo"><%= I18n.t('tog_social.groups.model.private_help') %></span>
      </p>
      <p>
        <label for="group_moderated" class="nolabel"><%= f.check_box :moderated %> <%= I18n.t('tog_social.groups.model.moderated') %></label><br/>
        <span class="helpinfo"><%= I18n.t('tog_social.groups.model.moderated_help') %></span>
      </p>
    </div>
    <div class="actions">
      <%= submit_tag I18n.t('tog_social.groups.site.create'), :class => "button mainaction" %>
    </div>
  </fieldset>
<% end %>

app/views/member/groups/pending_members.html.erb
<div class="detail detail1">
  
    <div class="image"><%=link_to image_for_group(@group, 'medium', :class=>"img"), group_path(@group)%></div>
    <div class="title"><%= link_to @group.name, group_path(@group) %></div>
    <div class="subtitle"><%= I18n.t('tog_social.groups.model.created_at') %> <%=h @group.created_at.strftime("%d/%m/%Y") %>, <%=@group.members.size%> members</div>
    <div class="summary"><%= I18n.t('tog_social.groups.model.moderated_by') %>:
        <% for moderator in @group.moderators %>
            <%=link_to moderator.profile.full_name, profile_path(moderator.profile), :class=> 'maincolor4'%>
        <% end %>
        <br/>
        <%= I18n.t('tog_social.tags.tags') %>: 
        <% for tag in @group.tag_list %>
          <%= link_to tag.to_s, tag_groups_path(tag) %>
        <% end %>   
    </div>
    
    <div class="portlet portletC" id="portlet_moreLinks">
        <h2><span><%= I18n.t('tog_social.groups.member.pending_members') %></span></h2>
        <div class="portlet_content">
            <ul>
                <% @group.pending_members.each do |user| %>
                  <li>
                    <%= link_to user.profile.full_name, profile_path(user.profile) -%> 
                    [<%= link_to I18n.t('tog_social.groups.member.accept'), member_group_accept_member_path(@group, user), {:class => "add", :title => I18n.t('tog_social.groups.member.accept_title')} -%>]               
                                 --
                    [<%= link_to I18n.t('tog_social.groups.member.reject'), member_group_reject_member_path(@group, user), {:class => "delete", :title => I18n.t('tog_social.groups.member.reject_title')} -%>]
                  </li>
                  <% end %>
            </ul>
        </div> 
    </div>    
    
</div> <!-- /.detail1 -->