config/routes.rb
# Add your custom routes here.  If in config/routes.rb you would
# add <tt>map.resources</tt>, here you would add just <tt>resources</tt>

resources :profiles

resources :streams, :only => [:index, :show]

with_options(:controller => 'groups') do |group|
  group.tag_groups       '/groups/tag/:tag',                         :action => 'tag'
end

resources :groups, :collection => { :search => :get }, :member => { :join => :get, :leave => :get }

namespace(:member) do |member|
  member.resources :profiles
  member.resources :groups
  member.with_options(:controller => 'groups') do |group|
    group.group_pending_members '/:id/members/pending',         :action => 'pending_members'
    group.group_accept_member   '/:id/members/:user_id/accept', :action => 'accept_member'
    group.group_reject_member   '/:id/members/:user_id/reject', :action => 'reject_member'
  end
  member.with_options(:controller => 'friendships') do |friendship|
    friendship.add_friend     '/friend/:friend_id/add',     :action => 'add_friend'
    friendship.confirm_friend '/friend/:friend_id/confirm', :action => 'confirm_friend'
    friendship.follow_user    '/follow/:friend_id',         :action => 'follow'
    friendship.unfollow_user  '/unfollow/:friend_id',       :action => 'unfollow'
  end
  member.with_options(:controller => 'sharings') do |sharing|
    sharing.share '/share/:shareable_type/:shareable_id', :action => 'index'
    sharing.share_with_group '/group/:id/share/:shareable_type/:shareable_id', :action => 'share'
  end
end

namespace(:admin) do |admin|
  admin.resources :groups, :member => { :activate => :post}
end

# => oauth support
resources :oauth_clients
authorize     '/oauth/authorize',     :controller=>'oauth', :action=>'authorize'
request_token '/oauth/request_token', :controller=>'oauth', :action=>'request_token'
access_token  '/oauth/access_token',  :controller=>'oauth', :action=>'access_token'
test_request  '/oauth/test_request',  :controller=>'oauth', :action=>'test_request'

x1 '/oauth_test',     :controller=>'oauth_test', :action=>'test'
x2 '/oauth_callback', :controller=>'oauth_test', :action=>'callback'
# => oauth support

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController

  def index
    @order = params[:order] || 'name'
    @page = params[:page] || '1'
    @groups = Group.paginate :per_page => 20,
                             :page => @page,
                             :order => "#{@order} ASC"
  end

  def edit
    @group = Group.find(params[:id])
  end
  
  def update
    @group = Group.find(params[:id])    
    @group.update_attributes!(params[:group])
    @group.save
    flash[:ok] =  I18n.t("tog_social.groups.admin.updated", :name => @group.name) 
    redirect_to edit_admin_group_path(@group)
  end  

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |wants|
      wants.html do
        flash[:ok]= I18n.t("tog_social.groups.admin.deleted")
        redirect_to admin_groups_path
      end
    end
  end

  def activate
    @group = Group.find(params[:id])
    @group.activate!
    respond_to do |wants|
      if @group.activate!
        wants.html do
          render :text => "<span>#{I18n.t("tog_social.groups.admin.activated")}</span>"
        end
      end
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :login_required, :only => [:join, :leave]
  before_filter :load_group, :only => [:show, :join, :leave, :members, :accept_invitation, :reject_invitation, :share]

  def index
    @order = params[:order] || 'created_at'
    @page = params[:page] || '1'
    @asc = params[:asc] || 'desc'
    @groups = Group.active.public.paginate  :per_page => 10,
                                            :page => @page,
                                            :order => @order + " " + @asc
    respond_to do |format|
      format.html
      format.rss { render(:layout => false) }
    end
  end

  def search
    @order = params[:order] || 'name'
    @page = params[:page] || '1'
    @search_term = params[:search_term]
    term = '%' + @search_term + '%'
    @asc = params[:asc] || 'asc'
    @groups = Group.active.public.paginate  :per_page => 10,
                                            :conditions => ["(name like ? or description like ?)", term, term],
                                            :page => @page,
                                            :order => @order + " " + @asc
    respond_to do |format|
       format.html { render :template => "groups/index"}
       format.xml  { render :xml => @groups }
    end
  end

  def show
  end

  def members
  end


  def tag
    @tag = params[:tag]
    @groups = Group.active.public.find_tagged_with(@tag)
    respond_to do |format|
      format.html # tag.html.erb
      format.xml  { render :xml => @groups.to_xml }
    end
  end

  def join
    if @group.members.include? current_user
      flash[:notice] = I18n.t("tog_social.groups.site.already_member")
    else
      if @group.pending_members.include? current_user
        flash[:notice] = I18n.t("tog_social.groups.site.request_waiting")
      else
        @group.join(current_user)
        if @group.moderated == true
          GroupMailer.deliver_join_request(@group, current_user)
          flash[:ok] = I18n.t("tog_social.groups.site.request_received")
        else
          @group.activate_membership(current_user)
          flash[:ok] = I18n.t("tog_social.groups.site.welcome", :name => @group.name)
        end
      end
    end
    redirect_to group_url(@group)
  end

  def leave
    if !@group.members.include?(current_user) && !@group.pending_members.include?(current_user)
      flash[:error] = I18n.t("tog_social.groups.site.not_member")
    else
      if @group.moderators.include?(current_user) && @group.moderators.size == 1
        flash[:error] = I18n.t("tog_social.groups.site.last_moderator")
      else
        @group.leave(current_user)
        #todo: eliminar cuando este claro que sucede si un usuario ya es miembro
        flash[:ok] = I18n.t("tog_social.groups.site.leaved")
      end
    end
    redirect_to member_groups_path
  end
  
  def accept_invitation
    if(@group.accept_invitation(current_user))
      flash[:ok] = I18n.t("tog_social.groups.site.invite.invitation_accepted")
    else
      flash[:error] = I18n.t("tog_social.groups.site.invite.you_are_not_invited")
    end
    redirect_to group_path(@group)
  end
  
  def reject_invitation
    if(@group.leave(current_user))
      flash[:ok] = I18n.t("tog_social.groups.site.invite.invitation_rejected")
    else
      flash[:error] = I18n.t("tog_social.groups.site.invite.you_are_not_invited")
    end
    redirect_to group_path(@group)
  end
  
  protected
    def load_group
      #TODO be more specific with this error control
      begin
        @group = Group.find(params[:id])
        raise I18n.t("tog_social.site.groups.unactive") unless @group.active?
      rescue
        flash[:error] = I18n.t("tog_social.groups.site.not_found")
        redirect_to groups_path
      end
    end

    def send_message_to_moderators(group, user, subject, body)
      group.moderators.each do |moderator|
        message = Message.new(
          :from     => user,
          :to       => moderator,
          :subject  => subject,
          :content  => body)
        message.dispatch!
      end
    end
end

app/controllers/member/groups_controller.rb
class Member::GroupsController < Member::BaseController

  before_filter :find_group, :except => [:index, :new, :create]
  before_filter :check_moderator, :except => [:index, :new, :create, :invite, :accept_invitation, :reject_invitation]

  def index
    @moderator_memberships = current_user.moderator_memberships
    @plain_memberships = current_user.plain_memberships
  end

  def create
    @group = Group.new(params[:group])
    @group.author = current_user
    @group.save


    if @group.errors.empty?

      @group.join(current_user, true)
      #    @group.activate_membership(current_user)

      if current_user.admin == true || Tog::Config['plugins.tog_social.group.moderation.creation'] != true
         @group.activate!
         flash[:ok] = I18n.t("tog_social.groups.member.created")
         redirect_to group_path(@group)
      else

        admins = User.find_all_by_admin(true)        
        admins.each do |admin|
          Message.new(
            :from => current_user,
            :to   => admin,
            :subject => I18n.t("tog_social.groups.member.mail.activation_request.subject", :group_name => @group.name),
            :content => I18n.t("tog_social.groups.member.mail.activation_request.content", 
                               :user_name   => current_user.profile.full_name, 
                               :group_name => @group.name, 
                               :activation_url => edit_admin_group_url(@group)) 
          ).dispatch!     
        end

        flash[:warning] = I18n.t("tog_social.groups.member.pending")
        redirect_to groups_path
      end
    else
      render :action => 'new'
    end

  end

  def update
    @group.update_attributes!(params[:group])
    @group.tag_list = params[:group][:tag_list]
    @group.save
    flash[:ok] =  I18n.t("tog_social.groups.member.updated", :name => @group.name) 
    redirect_to group_path(@group)
  end

  def reject_member
    user = User.find(params[:user_id])
    if !user
      flash[:error] = I18n.t("tog_social.groups.member.user_doesnot_exists")
      redirect_to pending_members_paths(@group)
      return
    end
    @group.leave(user)
    if @group.membership_of(user)
      GroupMailer.deliver_reject_join_request(@group, current_user, user)
      flash[:ok] = I18n.t("tog_social.groups.member.user_rejected", :name => user.profile.full_name) 
    else
      flash[:error] = I18n.t("tog_social.groups.member.error") 
    end
    redirect_to member_group_pending_members_url(@group)
  end

  def accept_member
    user = User.find(params[:user_id])
    if !user
      flash[:error] = I18n.t("tog_social.groups.member.user_doesnot_exists")
      redirect_to pending_members_paths(@group)
      return
    end
    @group.activate_membership(user)
    if @group.members.include? user
      GroupMailer.deliver_accept_join_request(@group, current_user, user)
      flash[:ok] = I18n.t("tog_social.groups.member.user_accepted", :name => user.profile.full_name)
    else
      flash[:error] = I18n.t("tog_social.groups.member.error") 
    end
    redirect_to member_group_pending_members_url(@group)
  end

  def invite
    @group = Group.find(params[:membership][:group_id])
    user = User.find(params[:membership][:user_id])
    if @group.can_invite?(current_user)
      if @group.members.include? user
        flash[:notice] = I18n.t("tog_social.groups.site.already_member")
      else
        if @group.invited_members.include? user
          flash[:error] = I18n.t("tog_social.groups.site.invite.already_invited")
        else
          @group.invite(user)
          @message = Message.new(
          :from => current_user,
          :to => user,
          :subject => I18n.t("tog_social.groups.member.mail.invitation.subject", :group=>@group.name),
          :content => render_to_string(:partial => 'invite_mail', :locals =>{:group=>@group})
          )
          @message.dispatch!
          flash[:ok] = I18n.t("tog_social.groups.site.invite.invited")
        end
      end
    else
      flash[:error] = flash[:error] = I18n.t("tog_social.groups.site.invite.you_could_not_invite")
    end
    redirect_to profile_path(user.profile)
  end

  protected


  def find_group
    @group = Group.find(params[:id]) if params[:id]
  end

  def check_moderator
    unless @group.moderators.include? current_user
      flash[:error] = I18n.t("tog_social.groups.member.not_moderator") 
      redirect_to group_path(@group)
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper

  def tag_cloud_groups(classes)
    tags = Group.tag_counts(:conditions => "state= 'active' and private = 0")
    return if tags.empty?
    max_count = tags.sort_by(&:count).last.count.to_f
    tags.each do |tag|
      index = ((tag.count / max_count) * (classes.size - 1)).round
      yield tag, classes[index]
    end
  end

  def image_for_group(group, size, options={})
    return if !group
    if group.image?
      photo_url = group.image.url(size)
      options.merge!(:alt => "Photo for group: #{group.name}")
      return image_tag(photo_url, options) if photo_url
    else
      return image_tag("/tog_social/images/#{config["plugins.tog_social.group.image.default"]}", options)
    end
  end


  def last_groups(limit=3)
    Group.find(:all,:conditions => ["state= ? and private = ?", 'active', false],:order => "created_at desc", :limit => limit)
  end


  def i_am_member_of(group)
    return group.members.include?(current_user)
  end
  def i_am_moderator_of(group)
    return group.moderators.include?(current_user)
  end

end

app/views/groups/_last_groups.html.erb
<div class="portlet portletJ" id="portlet_last_groups">
    <h2><span><%= I18n.t('tog_social.groups.site.last_groups') %></span></h2>
    <div class="portlet_content">
        <ul>
            <% last_groups(3).each do |group| -%>
              <li class="clearfix">
                  <div class="image"><%=link_to image_for_group(group, 'medium'), group_path(group)%></div>
                  <div class="title"><%= group.name -%></div>
                  <div class="text">
                      <%= I18n.t('tog_social.groups.model.created_at') %> <%=I18n.l(group.created_at, :format => :short)%>
                      <br/>
                      <%= I18n.t('tog_social.groups.model.members', :count => group.members.size) %>
                  </div>
                  <div class="more"><%= link_to I18n.t('tog_social.more_info'), group_path(group) -%></div>
              </li>            
            <% end -%>            
        </ul> 
    </div>    
</div> <!-- /.portlet_pluginsTog -->

app/views/groups/_search_box.html.erb
<form name="group_search" id="group_search" action="<%= search_groups_path %>">
  <label for="group_search_field"><%= I18n.t('tog_social.groups.site.search_groups') %></label>
  <input type="text" name="search_term" id="search_term" value="<%=@search_term%>" class="fieldbox" />
  <input type="submit" value="<%= I18n.t('tog_social.search') %>" class="button" />
</form>

app/views/groups/_tag_cloud.html.erb
<div class="portlet_tags">
  <div class="portlet_title"><strong><%= I18n.t('tog_social.groups.site.group_tags') %></strong></div>
  <div class="portlet_content">
    <ul>
      <% tag_cloud_groups %w(l1 l2 l3 l4 l5 l6 l7) do |tag, css_class| %>
        <li class="<%= css_class -%>"><%= link_to tag.name, tag_groups_path(tag.name) %></li>
      <% end -%>
    </ul>
  </div> <!-- .portlet_content --> 
</div>  <!-- .portlet_tags -->

app/views/groups/index.html.erb
<div class="portlet portletH" id="portlet_groups">
    <h2><span><%= I18n.t('tog_social.groups.site.title') %></span></h2>
    <p><%= link_to I18n.t('tog_social.groups.site.create_group'), new_member_group_path, :class => 'button add' %></p>
    <div class="portlet_content">
        <ul>
          <% @groups.each do |group|%>
          <li class="clearfix">
              <div class="image"><%=link_to image_for_group(group, 'medium'), group_path(group)%></div>
              <div class="title"><%= link_to group.name, group_path(group) %></div>
              <div class="text">
                 <%=group.description%>
              </div>
              <div class="members"><strong>
              <%= I18n.t('tog_social.groups.model.members', :count => group.members.size) %></strong></div>
          </li>          
          <%end%>          
        </ul>
    </div>    
</div>


<%= will_paginate @groups %>

<% content_for :sidebar do %>

  <% 'render :partial => "search_box" ' %>

  <%= render :partial => "last_groups" %>

<% end %>

app/views/groups/show.html.erb
<div class="detail detail1">
  <div class="image"><%= link_to image_for_group(@group, 'medium', :class=>"img"), group_path(@group) %></div>
  <div class="title"><%= link_to @group.name, group_path(@group) %></div>
  <div class="subtitle"><%= I18n.t('tog_social.groups.model.created_at') %> <%= @group.created_at.strftime("%d/%m/%Y") %>, <%= I18n.t('tog_social.groups.model.members', :count => @group.members.size) %></div>
  <div class="summary"><%= I18n.t('tog_social.groups.model.moderated_by') %>:
    <% for moderator in @group.moderators -%>
      <%=link_to moderator.profile.full_name, profile_path(moderator.profile), :class=> 'maincolor4'%>
    <% end -%>
    <br/>
    <%= I18n.t('tog_social.tags.tags') %>: 
      <% for tag in @group.tag_list %>
        <%= link_to tag.to_s, tag_groups_path(tag) %>
      <% end %>   
  </div>
  <div class="text">
    <p><%= @group.description %></p>
  </div>
</div> <!-- /.detail1 --> 

<% content_for :sidebar do %>

<div class="portlet portletC" id="portlet_moreLinks">
    <h2><span><%= I18n.t('tog_social.more_links') %></span></h2>
    <div class="portlet_content">
        <ul>
          <% if i_am_member_of @group -%>
            <li><%= I18n.t('tog_social.groups.site.member') %><%= link_to I18n.t('tog_social.groups.site.leave'), leave_group_path(@group), :confirm => I18n.t('tog_social.groups.site.leave_confirm'), :class => 'delete' %></li>
          <% else -%>
            <li><%= link_to I18n.t('tog_social.groups.site.join'), join_group_path(@group), :class => 'add' %></li>
          <% end -%>  
        </ul>
    </div> 
</div>    

<%= render :partial => "shared/profiles_portlet", :locals => { 
  :items => @group.members.collect(&:profile), 
  :style => :portletG, 
  :title => I18n.t('tog_social.groups.model.members', :count => @group.members.size),  
  :no_items => I18n.t('tog_social.groups.model.members_not_found', :group_name => @group.name) } %>
<% end %>

app/views/groups/tag.html.erb
<div class="portlet portletH" id="portlet_groups">
    <h2><span><%= I18n.t('tog_social.groups.site.group_tagged', :tag => @tag) %></span></h2>
    <p><%= link_to I18n.t('tog_social.groups.site.create_group'), new_member_group_path, :class => 'button add' %></p>
    <div class="portlet_content">
        <ul>
          <% @groups.each do |group|%>
          <li class="clearfix">
              <div class="image"><%=link_to image_for_group(group, 'medium'), group_path(group)%></div>
              <div class="title"><%= link_to group.name, group_path(group) %></div>
              <div class="text">
                 <%=group.description%>
              </div>
              <div class="members"><strong>
              <%= I18n.t('tog_social.groups.model.members', :count => group.members.size) %></strong></div>
          </li>          
          <%end%>          
        </ul>
    </div>    
</div>

<% content_for :sidebar do %>

  <% 'render :partial => "search_box" ' %>

  <%= render :partial => "last_groups" %>

<% end %>