config/routes.rb
# Add your custom routes here.  If in config/routes.rb you would
# add <tt>map.resources</tt>, here you would add just <tt>resources</tt>

resources :profiles

resources :streams, :only => [:index, :show]

with_options(:controller => 'groups') do |group|
  group.tag_groups       '/groups/tag/:tag',                         :action => 'tag'
end

resources :groups, :collection => { :search => :get }, :member => { :join => :get, :leave => :get }

namespace(:member) do |member|
  member.resources :profiles
  member.resources :groups
  member.with_options(:controller => 'groups') do |group|
    group.group_pending_members '/:id/members/pending',         :action => 'pending_members'
    group.group_accept_member   '/:id/members/:user_id/accept', :action => 'accept_member'
    group.group_reject_member   '/:id/members/:user_id/reject', :action => 'reject_member'
  end
  member.with_options(:controller => 'friendships') do |friendship|
    friendship.add_friend     '/friend/:friend_id/add',     :action => 'add_friend'
    friendship.confirm_friend '/friend/:friend_id/confirm', :action => 'confirm_friend'
    friendship.follow_user    '/follow/:friend_id',         :action => 'follow'
    friendship.unfollow_user  '/unfollow/:friend_id',       :action => 'unfollow'
  end
  member.with_options(:controller => 'sharings') do |sharing|
    sharing.share '/share/:shareable_type/:shareable_id', :action => 'index'
    sharing.share_with_group '/group/:id/share/:shareable_type/:shareable_id', :action => 'share'
  end
end

namespace(:admin) do |admin|
  admin.resources :groups, :member => { :activate => :post}
end

# => oauth support
resources :oauth_clients
authorize     '/oauth/authorize',     :controller=>'oauth', :action=>'authorize'
request_token '/oauth/request_token', :controller=>'oauth', :action=>'request_token'
access_token  '/oauth/access_token',  :controller=>'oauth', :action=>'access_token'
test_request  '/oauth/test_request',  :controller=>'oauth', :action=>'test_request'

x1 '/oauth_test',     :controller=>'oauth_test', :action=>'test'
x2 '/oauth_callback', :controller=>'oauth_test', :action=>'callback'
# => oauth support

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController

  def index
    @order = params[:order] || 'name'
    @page = params[:page] || '1'
    @groups = Group.paginate :per_page => 20,
                             :page => @page,
                             :order => "#{@order} ASC"
  end

  def edit
    @group = Group.find(params[:id])
  end
  
  def update
    @group = Group.find(params[:id])    
    @group.update_attributes!(params[:group])
    @group.save
    flash[:ok] =  I18n.t("tog_social.groups.admin.updated", :name => @group.name) 
    redirect_to edit_admin_group_path(@group)
  end  

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |wants|
      wants.html do
        flash[:ok]= I18n.t("tog_social.groups.admin.deleted")
        redirect_to admin_groups_path
      end
    end
  end

  def activate
    @group = Group.find(params[:id])
    @group.activate!
    respond_to do |wants|
      if @group.activate!
        wants.html do
          render :text => "<span>#{I18n.t("tog_social.groups.admin.activated")}</span>"
        end
      end
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :login_required, :only => [:join, :leave]
  before_filter :load_group, :only => [:show, :join, :leave, :members, :accept_invitation, :reject_invitation, :share]

  def index
    @order = params[:order] || 'created_at'
    @page = params[:page] || '1'
    @asc = params[:asc] || 'desc'
    @groups = Group.active.public.paginate  :per_page => 10,
                                            :page => @page,
                                            :order => @order + " " + @asc
    respond_to do |format|
      format.html
      format.rss { render(:layout => false) }
    end
  end

  def search
    @order = params[:order] || 'name'
    @page = params[:page] || '1'
    @search_term = params[:search_term]
    term = '%' + @search_term + '%'
    @asc = params[:asc] || 'asc'
    @groups = Group.active.public.paginate  :per_page => 10,
                                            :conditions => ["(name like ? or description like ?)", term, term],
                                            :page => @page,
                                            :order => @order + " " + @asc
    respond_to do |format|
       format.html { render :template => "groups/index"}
       format.xml  { render :xml => @groups }
    end
  end

  def show
  end

  def members
  end


  def tag
    @tag = params[:tag]
    @groups = Group.active.public.find_tagged_with(@tag)
    respond_to do |format|
      format.html # tag.html.erb
      format.xml  { render :xml => @groups.to_xml }
    end
  end

  def join
    if @group.members.include? current_user
      flash[:notice] = I18n.t("tog_social.groups.site.already_member")
    else
      if @group.pending_members.include? current_user
        flash[:notice] = I18n.t("tog_social.groups.site.request_waiting")
      else
        @group.join(current_user)
        if @group.moderated == true
          GroupMailer.deliver_join_request(@group, current_user)
          flash[:ok] = I18n.t("tog_social.groups.site.request_received")
        else
          @group.activate_membership(current_user)
          flash[:ok] = I18n.t("tog_social.groups.site.welcome", :name => @group.name)
        end
      end
    end
    redirect_to group_url(@group)
  end

  def leave
    if !@group.members.include?(current_user) && !@group.pending_members.include?(current_user)
      flash[:error] = I18n.t("tog_social.groups.site.not_member")
    else
      if @group.moderators.include?(current_user) && @group.moderators.size == 1
        flash[:error] = I18n.t("tog_social.groups.site.last_moderator")
      else
        @group.leave(current_user)
        #todo: eliminar cuando este claro que sucede si un usuario ya es miembro
        flash[:ok] = I18n.t("tog_social.groups.site.leaved")
      end
    end
    redirect_to member_groups_path
  end
  
  def accept_invitation
    if(@group.accept_invitation(current_user))
      flash[:ok] = I18n.t("tog_social.groups.site.invite.invitation_accepted")
    else
      flash[:error] = I18n.t("tog_social.groups.site.invite.you_are_not_invited")
    end
    redirect_to group_path(@group)
  end
  
  def reject_invitation
    if(@group.leave(current_user))
      flash[:ok] = I18n.t("tog_social.groups.site.invite.invitation_rejected")
    else
      flash[:error] = I18n.t("tog_social.groups.site.invite.you_are_not_invited")
    end
    redirect_to group_path(@group)
  end
  
  protected
    def load_group
      #TODO be more specific with this error control
      begin
        @group = Group.find(params[:id])
        raise I18n.t("tog_social.site.groups.unactive") unless @group.active?
      rescue
        flash[:error] = I18n.t("tog_social.groups.site.not_found")
        redirect_to groups_path
      end
    end

    def send_message_to_moderators(group, user, subject, body)
      group.moderators.each do |moderator|
        message = Message.new(
          :from     => user,
          :to       => moderator,
          :subject  => subject,
          :content  => body)
        message.dispatch!
      end
    end
end

app/controllers/member/groups_controller.rb
class Member::GroupsController < Member::BaseController

  before_filter :find_group, :except => [:index, :new, :create]
  before_filter :check_moderator, :except => [:index, :new, :create, :invite, :accept_invitation, :reject_invitation]

  def index
    @moderator_memberships = current_user.moderator_memberships
    @plain_memberships = current_user.plain_memberships
  end

  def create
    @group = Group.new(params[:group])
    @group.author = current_user
    @group.save


    if @group.errors.empty?

      @group.join(current_user, true)
      #    @group.activate_membership(current_user)

      if current_user.admin == true || Tog::Config['plugins.tog_social.group.moderation.creation'] != true
         @group.activate!
         flash[:ok] = I18n.t("tog_social.groups.member.created")
         redirect_to group_path(@group)
      else

        admins = User.find_all_by_admin(true)        
        admins.each do |admin|
          Message.new(
            :from => current_user,
            :to   => admin,
            :subject => I18n.t("tog_social.groups.member.mail.activation_request.subject", :group_name => @group.name),
            :content => I18n.t("tog_social.groups.member.mail.activation_request.content", 
                               :user_name   => current_user.profile.full_name, 
                               :group_name => @group.name, 
                               :activation_url => edit_admin_group_url(@group)) 
          ).dispatch!     
        end

        flash[:warning] = I18n.t("tog_social.groups.member.pending")
        redirect_to groups_path
      end
    else
      render :action => 'new'
    end

  end

  def update
    @group.update_attributes!(params[:group])
    @group.tag_list = params[:group][:tag_list]
    @group.save
    flash[:ok] =  I18n.t("tog_social.groups.member.updated", :name => @group.name) 
    redirect_to group_path(@group)
  end

  def reject_member
    user = User.find(params[:user_id])
    if !user
      flash[:error] = I18n.t("tog_social.groups.member.user_doesnot_exists")
      redirect_to pending_members_paths(@group)
      return
    end
    @group.leave(user)
    if @group.membership_of(user)
      GroupMailer.deliver_reject_join_request(@group, current_user, user)
      flash[:ok] = I18n.t("tog_social.groups.member.user_rejected", :name => user.profile.full_name) 
    else
      flash[:error] = I18n.t("tog_social.groups.member.error") 
    end
    redirect_to member_group_pending_members_url(@group)
  end

  def accept_member
    user = User.find(params[:user_id])
    if !user
      flash[:error] = I18n.t("tog_social.groups.member.user_doesnot_exists")
      redirect_to pending_members_paths(@group)
      return
    end
    @group.activate_membership(user)
    if @group.members.include? user
      GroupMailer.deliver_accept_join_request(@group, current_user, user)
      flash[:ok] = I18n.t("tog_social.groups.member.user_accepted", :name => user.profile.full_name)
    else
      flash[:error] = I18n.t("tog_social.groups.member.error") 
    end
    redirect_to member_group_pending_members_url(@group)
  end

  def invite
    @group = Group.find(params[:membership][:group_id])
    user = User.find(params[:membership][:user_id])
    if @group.can_invite?(current_user)
      if @group.members.include? user
        flash[:notice] = I18n.t("tog_social.groups.site.already_member")
      else
        if @group.invited_members.include? user
          flash[:error] = I18n.t("tog_social.groups.site.invite.already_invited")
        else
          @group.invite(user)
          @message = Message.new(
          :from => current_user,
          :to => user,
          :subject => I18n.t("tog_social.groups.member.mail.invitation.subject", :group=>@group.name),
          :content => render_to_string(:partial => 'invite_mail', :locals =>{:group=>@group})
          )
          @message.dispatch!
          flash[:ok] = I18n.t("tog_social.groups.site.invite.invited")
        end
      end
    else
      flash[:error] = flash[:error] = I18n.t("tog_social.groups.site.invite.you_could_not_invite")
    end
    redirect_to profile_path(user.profile)
  end

  protected


  def find_group
    @group = Group.find(params[:id]) if params[:id]
  end

  def check_moderator
    unless @group.moderators.include? current_user
      flash[:error] = I18n.t("tog_social.groups.member.not_moderator") 
      redirect_to group_path(@group)
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper

  def tag_cloud_groups(classes)
    tags = Group.tag_counts(:conditions => "state= 'active' and private = 0")
    return if tags.empty?
    max_count = tags.sort_by(&:count).last.count.to_f
    tags.each do |tag|
      index = ((tag.count / max_count) * (classes.size - 1)).round
      yield tag, classes[index]
    end
  end

  def image_for_group(group, size, options={})
    return if !group
    if group.image?
      photo_url = group.image.url(size)
      options.merge!(:alt => "Photo for group: #{group.name}")
      return image_tag(photo_url, options) if photo_url
    else
      return image_tag("/tog_social/images/#{config["plugins.tog_social.group.image.default"]}", options)
    end
  end


  def last_groups(limit=3)
    Group.find(:all,:conditions => ["state= ? and private = ?", 'active', false],:order => "created_at desc", :limit => limit)
  end


  def i_am_member_of(group)
    return group.members.include?(current_user)
  end
  def i_am_moderator_of(group)
    return group.moderators.include?(current_user)
  end

end

app/views/admin/groups/edit.html.erb
<h1><%= link_to I18n.t("tog_social.groups.admin.groups"), admin_groups_path%> / <%=  @group.name -%></h1>

<p>
  <% unless @group.active? %>
    <span id="deactivated_status">
    <%= link_to_remote I18n.t("tog_social.groups.admin.activate"),  :url => activate_admin_group_url(@group), :update => "deactivated_status", :html => {:class => 'button'} %>
    </span>
  <% end %>
  <% form_tag admin_group_path(@group), :method => :delete do -%>
    <%= submit_tag I18n.t("tog_social.groups.admin.delete_group"), :disable_with => I18n.t("tog_social.groups.admin.please_wait"), :class =>"button delete" %>
  <% end -%>
</p>

<br/>


<table class="tableE">
  <caption><%= I18n.t("tog_social.groups.admin.group_details") %></caption>
  <tbody>
  <tr><th scope="row"><%= I18n.t("tog_social.groups.model.name") %></th><td><%=@group.name%></td></tr>
  <tr><th scope="row"><%= I18n.t("tog_social.groups.model.icon") %></th><td><%= image_for_group(@group, 'medium') if @group.image %></td></tr>
  <tr><th scope="row"><%= I18n.t("tog_social.groups.model.created_by") %></th><td><%= link_to @group.author.profile.full_name, edit_admin_user_path(@group.author) if @group.author %></td></tr>
  <tr><th scope="row"><%= I18n.t("tog_social.groups.model.created_at") %></th><td><%=@group.creation_date%></td></tr>
  </tbody>
</table>

<table class="tableE">
  <caption><%= I18n.t("tog_social.groups.admin.memberships") %></caption>
  <tbody>
  <tr><th scope="row"><%= I18n.t("tog_social.groups.admin.moderators") %></th>
      <td>
        <%= @group.moderators.size %>
        <br/>
        <% for member in @group.moderators %>
        <li><%= link_to member.profile.full_name, edit_admin_user_path(member) %> (<%= member.email %>)</li>
        <% end %>
      </td>
  </tr>
  <tr><th scope="row"><%= I18n.t("tog_social.groups.admin.members") %></th><td><%=@group.members.size%></td></tr>
  <tr><th scope="row"><%= I18n.t("tog_social.groups.admin.pending_members") %></th><td><%=@group.pending_members.size%></td></tr>
  </tbody>
</table>

<br />

app/views/admin/groups/index.html.erb
<h1><%= I18n.t("tog_social.groups.admin.groups") %></h1>

<table class="tableE">
  <thead>
    <tr>
      <th scope="col"><%= I18n.t("tog_social.groups.model.name") -%></th>
      <th scope="col"><%= I18n.t("tog_social.groups.model.created_by") -%></th>
      <th scope="col"><%= I18n.t("tog_social.groups.model.private") -%></th>
      <th scope="col"><%= I18n.t("tog_social.groups.model.moderated") -%></th>
      <th scope="col"><%= I18n.t("tog_social.groups.model.active") -%></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td colspan="5" class="info_results">
        <span class="info_items"><%= page_entries_info @groups %></span>
        <span class="pages_navigation right">
          <%= will_paginate @groups, :container => false %>
        </span>
        </td>
    </tr>
  </tfoot>  
  <tbody>
    <% @groups.each do |group| %>
    <tr<%= cycle('',' class="pair"') -%>>
      <td><%= link_to group.name, edit_admin_group_url(group), {:class => "admin", :title => I18n.t("tog_social.groups.admin.edit_group")} -%></td>
      <td><%= link_to group.author.profile.full_name, edit_admin_user_path(group.author) if group.author %></td>
      <td><%= group.private == true ? I18n.t("tog_social.msg_yes") : I18n.t("tog_social.msg_no") -%></td>
      <td><%= group.moderated == true ? I18n.t("tog_social.msg_yes") : I18n.t("tog_social.msg_no") -%></td>
      <td><%= group.active? == true ? I18n.t("tog_social.msg_yes") : I18n.t("tog_social.msg_no")  -%></td>
    </tr>
    <% end %>
  </tbody>
</table>